//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert
    {
        public int adId { get; set; }
        public string adHeaderDesc { get; set; }
        public string adDesc { get; set; }
        public string adTab { get; set; }
        public string adImage { get; set; }
    }
}
