//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adverts_Images
    {
        public int Id { get; set; }
        public string imgUrl { get; set; }
        public Nullable<int> bagId { get; set; }
        public Nullable<bool> isdelete { get; set; }
    }
}
