//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketCevaplamaSonu
    {
        public int Id { get; set; }
        public Nullable<int> AnketId { get; set; }
        public int AnketCevaplariId { get; set; }
        public int MekanId { get; set; }
        public string Oneri { get; set; }
        public string AdiSoyadi { get; set; }
        public string Eposta { get; set; }
        public string TeL { get; set; }
        public System.DateTime Ktarihi { get; set; }
    
        public virtual AnketCevaplari AnketCevaplari { get; set; }
        public virtual Anketler Anketler { get; set; }
        public virtual Mekanlar Mekanlar { get; set; }
    }
}
