//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anketler()
        {
            this.AnketCevaplamaSonus = new HashSet<AnketCevaplamaSonu>();
            this.AnketCevaplaris = new HashSet<AnketCevaplari>();
            this.AnketSorularis = new HashSet<AnketSorulari>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public System.DateTime KTarihi { get; set; }
        public bool IletisimBilgiMecburiMi { get; set; }
        public Nullable<int> MekanId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevaplamaSonu> AnketCevaplamaSonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevaplari> AnketCevaplaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketSorulari> AnketSorularis { get; set; }
        public virtual Mekanlar Mekanlar { get; set; }
    }
}
