//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketCevaplari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnketCevaplari()
        {
            this.AnketCevaplamaSonus = new HashSet<AnketCevaplamaSonu>();
        }
    
        public int Id { get; set; }
        public int AnketId { get; set; }
        public int SoruId { get; set; }
        public string Yorum { get; set; }
        public Nullable<int> SecenekId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevaplamaSonu> AnketCevaplamaSonus { get; set; }
        public virtual Anketler Anketler { get; set; }
        public virtual AnketSorulariSecenekleri AnketSorulariSecenekleri { get; set; }
        public virtual AnketSorulari AnketSorulari { get; set; }
    }
}
