//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyValue
    {
        public int CompanyValueId { get; set; }
        public string CompanyValuesPhotos { get; set; }
        public string CompanyValuesTitle { get; set; }
        public string CompanyValuesDescription { get; set; }
    }
}
