//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contactId { get; set; }
        public string contactImageSrc { get; set; }
        public string contactPhoneNumber { get; set; }
        public string contactFaxNumber { get; set; }
        public string contactAddress { get; set; }
    }
}
