//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int footerId { get; set; }
        public string footerLogo { get; set; }
        public string footerLocalNumber { get; set; }
        public string footerGsmNumber { get; set; }
        public string footerDesc { get; set; }
        public string footerLogo2 { get; set; }
    }
}
