//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralManager
    {
        public int GeneralManagerId { get; set; }
        public string GeneralManagerLogo { get; set; }
        public string GeneralManagerDescription { get; set; }
        public string GeneralManagerName { get; set; }
    }
}
