//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        public int headerId { get; set; }
        public string headerLogo { get; set; }
        public string headerAddress { get; set; }
        public string headerPhoneNumber { get; set; }
        public string headerFaxNumber { get; set; }
        public string headerPresidentLogo { get; set; }
        public string headerPresidentName { get; set; }
        public string headerPresidentDescription { get; set; }
    }
}
