//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplicationForm
    {
        public int Id { get; set; }
        public string BasvurulanPozisyon { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string CepTel { get; set; }
        public string CVUrl { get; set; }
    }
}
