//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Activities_Images> Activities_Images { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Advert> Adverts { get; set; }
        public virtual DbSet<Adverts_Images> Adverts_Images { get; set; }
        public virtual DbSet<AnketCevaplamaSonu> AnketCevaplamaSonus { get; set; }
        public virtual DbSet<AnketCevaplari> AnketCevaplaris { get; set; }
        public virtual DbSet<Anketler> Anketlers { get; set; }
        public virtual DbSet<AnketSorulari> AnketSorularis { get; set; }
        public virtual DbSet<AnketSorulariSecenekleri> AnketSorulariSecenekleris { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<CompanyValue> CompanyValues { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Footer> Footers { get; set; }
        public virtual DbSet<GaleriBasliklari> GaleriBasliklaris { get; set; }
        public virtual DbSet<GeneralManager> GeneralManagers { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
        public virtual DbSet<HumanResource> HumanResources { get; set; }
        public virtual DbSet<Identity> Identities { get; set; }
        public virtual DbSet<JobApplicationForm> JobApplicationForms { get; set; }
        public virtual DbSet<Kvkk> Kvkks { get; set; }
        public virtual DbSet<Mekanlar> Mekanlars { get; set; }
        public virtual DbSet<Mission> Missions { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_Images> News_Images { get; set; }
        public virtual DbSet<OrganizationChart> OrganizationCharts { get; set; }
        public virtual DbSet<OurService> OurServices { get; set; }
        public virtual DbSet<PageHeader> PageHeaders { get; set; }
        public virtual DbSet<PhotoGalery> PhotoGaleries { get; set; }
        public virtual DbSet<PrePayment> PrePayments { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<SSSorular> SSSorulars { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vision> Visions { get; set; }
        public virtual DbSet<Whatwedo> Whatwedoes { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<SubsFormService> SubsFormServices { get; set; }
        public virtual DbSet<SubscriptionForm> SubscriptionForms { get; set; }
    }
}
