//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OurService()
        {
            this.SubsFormServices = new HashSet<SubsFormService>();
        }
    
        public int Id { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string Adress { get; set; }
        public string Title { get; set; }
        public string Subtitile { get; set; }
        public string WorkingHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubsFormService> SubsFormServices { get; set; }
    }
}
