//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageHeader
    {
        public int pageHeaderId { get; set; }
        public string aboutHeader { get; set; }
        public string visionHeader { get; set; }
        public string missionHeader { get; set; }
        public string photoGaleryHeader { get; set; }
        public string contactHeader { get; set; }
        public string whatwedoHeader { get; set; }
        public string newsHeader { get; set; }
        public string advertsHeader { get; set; }
        public string activityHeader { get; set; }
    }
}
