//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsFormService
    {
        public int Id { get; set; }
        public Nullable<int> OurServiceId { get; set; }
        public Nullable<int> SubsFormId { get; set; }
    
        public virtual OurService OurService { get; set; }
        public virtual SubscriptionForm SubscriptionForm { get; set; }
    }
}
