//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whatwedo
    {
        public int whatwedoId { get; set; }
        public string whatwedoHeaderDesc { get; set; }
        public string whatwedoDesc { get; set; }
    }
}
