//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurService
    {
        public int Id { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string Adress { get; set; }
        public string Title { get; set; }
        public string Subtitile { get; set; }
        public string WorkingHours { get; set; }
    }
}
